Repository Play-Arcade/Play-ArcadeWeb, pull requests merged in 2020-02, with the labels that each got.

#9 mongoose database connection
  .gitignore
  server/app.js
  server/package-lock.json
  server/package.json
Labels: Back-End, Database

#14 Fix/new sv gs
  client/TabContent.js
  client/Tabs.js
  client/main.js
  index.html
  resources/joinus/Join Us.svg
  resources/joinus/alphaAccess.png
  resources/joinus/crowdfund.png
  resources/joinus/development.png
  resources/joinus/investor.png
  resources/joinus/joinus-frame.svg
  resources/joinus/joinusCards.png
  resources/joinus/newsletter.png
  resources/joinus/partnerwithus.png
  resources/milestones/Milestones.svg
  resources/milestones/milestones-frame.svg
  resources/solution/Solution.svg
  resources/solution/account 1.png
  resources/solution/cloud-computing 1.png
  resources/solution/global-server 1.png
  resources/solution/makerActive.svg
  resources/solution/pie-chart 1.png
  resources/solution/playerActive.svg
  resources/solution/solution-frame.svg
  resources/story/Story.svg
  resources/story/earlyDays.png
  resources/story/earlyDays.svg
  resources/story/story-frame.svg
  resources/story/summer.svg
  resources/vision/Vision.svg
  resources/vision/heroo.png
  resources/vision/sharejoy.svg
  resources/vision/text.svg
  resources/vision/vision-frame.svg
Labels: Front-End

#19 Apiendpoint
  server/app.js
  server/routes/form.js
  server/routes/index.js
Labels: Back-End, HTTP Query, Query Handler
